project_id = "ngbniovozalshujbpjoq"

[functions.pos-deduct]
verify_jwt = false

[functions.stock-check]
verify_jwt = false

[functions.pos-refund]
verify_jwt = false

[functions.sku-lookup]
verify_jwt = false

[functions.get-pos-data-for-fwteam]
verify_jwt = false